// Comprehensive list of educational subjects for random suggestion
export const SUBJECT_SUGGESTIONS = [
  // Traditional Academic Subjects
  "Mathematics",
  "Physics",
  "Chemistry",
  "Biology",
  "History",
  "Geography",
  "Literature",
  "Philosophy",
  "Psychology",
  "Sociology",
  "Economics",
  "Political Science",
  "Anthropology",
  "Archaeology",
  "Linguistics",

  // STEM & Technology
  "Computer Science",
  "Engineering",
  "Robotics",
  "Artificial Intelligence",
  "Data Science",
  "Cybersecurity",
  "Web Development",
  "Game Development",
  "Biotechnology",
  "Environmental Science",
  "Astronomy",
  "Geology",
  "Meteorology",
  "Marine Biology",
  "Genetics",

  // Arts & Creative
  "Art History",
  "Music Theory",
  "Film Studies",
  "Photography",
  "Creative Writing",
  "Theater Arts",
  "Dance",
  "Graphic Design",
  "Architecture",
  "Fashion Design",
  "Animation",
  "Digital Art",

  // Languages
  "Spanish",
  "French",
  "German",
  "Italian",
  "Japanese",
  "Chinese",
  "Arabic",
  "Russian",
  "Portuguese",
  "Korean",
  "Hindi",
  "Latin",

  // Health & Medicine
  "Medicine",
  "Nutrition",
  "Anatomy",
  "Physiology",
  "Public Health",
  "Mental Health",
  "Sports Medicine",
  "Veterinary Science",
  "Pharmacology",
  "Neuroscience",

  // Business & Finance
  "Business Management",
  "Marketing",
  "Finance",
  "Accounting",
  "Entrepreneurship",
  "International Business",
  "Human Resources",
  "Supply Chain Management",

  // Practical Skills
  "Cooking",
  "Gardening",
  "Woodworking",
  "Electronics",
  "Mechanics",
  "Plumbing",
  "First Aid",
  "Photography",
  "Public Speaking",
  "Time Management",

  // Specialized Fields
  "Criminology",
  "Forensic Science",
  "Journalism",
  "Law",
  "Education",
  "Social Work",
  "Urban Planning",
  "Agriculture",
  "Renewable Energy",
  "Space Science",
  "Climate Science",
  "Oceanography",
  "Paleontology",
  "Mythology",
  "Ethics",
  "Logic",
  "Statistics",
  "Game Theory",
  "Quantum Physics",
  "Molecular Biology",
];

// Adventure prompt suggestions (moved from AdventureGenerator)
export const ADVENTURE_PROMPTS = [
  "A space station mysteriously loses contact with Earth",
  "A detective investigating crimes in Victorian London",
  "A time traveler trying to prevent a historical disaster",
  "An underwater explorer discovering an ancient civilization",
  "A cyberpunk hacker uncovering a corporate conspiracy",
  "A fantasy quest to find a magical artifact",
  "A post-apocalyptic survivor searching for a safe haven",
  "A mystery in a haunted mansion during a dinner party",
  "A magical library where students learn ancient knowledge",
  "A time-travel journey into biblical times meeting Bible characters",
  "A robot uprising in a futuristic megacity",
  "A treasure hunter exploring cursed ancient ruins",
  "A small town with a dark supernatural secret",
  "A group of friends on a road trip to a mysterious destination",
  "A superhero needs to save the world from a dangerous villain",
  "A super spy uncovering a global conspiracy",
  "A medieval knight on a quest to save the kingdom",
  "An archaeologist discovering a lost civilization",
  "A pirate treasure hunt on a mysterious island",
  "A scientist experimenting with dangerous technology",
  "A group of students trapped in a magical school",
  "A journey through different dimensions and realities",
  "A survival story on an alien planet",
  "A mystery involving ancient Egyptian tombs",
  "A Wild West adventure with outlaws and sheriffs",
  "A steampunk inventor creating amazing machines",
];
